const ELECTRON_COMMANDS = {
  SELECT_FILE: "Select a File",
  SELECT_FOLDER: "Select a Folder",
  GUANFU: "Upscale the Image",
  GUANFU_DONE: "Upscaling Done",
  GUANFU_PROGRESS: "Send Progress from Main to Renderer",
  DOUBLE_GUANFU: "Double Upscale the Image",
  DOUBLE_GUANFU_DONE: "Double Upscaling Done",
  DOUBLE_GUANFU_PROGRESS: "Send Double Guanfu Progress from Main to Renderer",
  FOLDER_GUANFU: "Upscale a Folder",
  FOLDER_GUANFU_DONE: "Folder upscaling successful",
  FOLDER_GUANFU_PROGRESS:
    "Send Folder Upscaling Progress from Main to Renderer",
  OPEN_FOLDER: "Open Folder",
  GUANFU_VIDEO: "Upscale the Video",
  GUANFU_VIDEO_DONE: "Video Upscaling Done",
  GUANFU_VIDEO_PROGRESS: "Send Video Upscale Progress from Main to Renderer",
  FFMPEG_VIDEO_DONE: "Ran FFMpeg successfully",
  FFMPEG_VIDEO_PROGRESS: "Running FFMpeg for frame extraction",
  SELECT_CUSTOM_MODEL_FOLDER: "Select a Custom Model Folder",
  GET_MODELS_LIST: "Send models list from main to renderer",
  CUSTOM_MODEL_FILES_LIST: "Send custom model files list to renderer",
  LOG: "Log",
  STOP: "Stop the current operation",
  OS: "Get OS",
  SCALING_AND_CONVERTING: "Adding some finishing touches",
  GUANFU_WARNING: "Upscaling Warning",
  GUANFU_ERROR: "Upscaling Error",
  METADATA_ERROR: "Metadata Error",
  PASTE_IMAGE: "Paste Image from clipboard",
  PASTE_IMAGE_SAVE_SUCCESS: "Clipboard Image saved successfully",
  PASTE_IMAGE_SAVE_ERROR: "Clipboard Image save failed",
} as const;

export { ELECTRON_COMMANDS };
